services:
  api:
    container_name: tekra_boy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - openvpn
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"

  openvpn:
    image: kylemanna/openvpn
    container_name: vpn_server
    sysctls:
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn_data:/etc/openvpn
    networks:
      - backend

networks:
  backend:
    driver: host 

volumes:
  openvpn_data: